export APP_URI=YOUR APP URI
export AWS_ACCESS_KEY_ID= YOUR AWS ACCESS KEY ID
export AWS_SECRET_ACCESS_KEY= YOUR AWS SECRET ACCESS KEY
export BACKEND_STORE_URI= YOUR SQL LINK TO MLFLOW
export ARTIFACT_STORE_URI= BUCKET S3 URI
export MLFLOW_TRACKING_URI = YOUR MLFLOW URL